version: '3.8'

services:
  monolith:
    build: ./server
    container_name: kineo_monolith
    environment:
      - MONGODB_URI=mongodb+srv://admin:KineoDB2026@cluster0.0krkoks.mongodb.net/kineo?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - kineo_net

  dizionario:
    build: ./microservice-dizionario
    container_name: kineo_dizionario
    environment:
      - MONGODB_URI=mongodb+srv://admin:KineoDB2026@cluster0.0krkoks.mongodb.net/kineo?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - kineo_net

  catalogo:
    build: ./microservice-catalogo
    container_name: kineo_catalogo
    environment:
      - MONGODB_URI=mongodb+srv://admin:KineoDB2026@cluster0.0krkoks.mongodb.net/kineo?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - kineo_net

  kong:
    image: kong:3.6.1-ubuntu
    container_name: kineo_gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml
    networks:
      - kineo_net
    depends_on:
      - monolith
      - dizionario
      - catalogo

networks:
  kineo_net:
    driver: bridge